version: "3.9"

services:
  authservice_db:
    image: redis:alpine
    container_name: auth_redis
    command: redis-server --requirepass secret-redis
    ports:
      - "6379:6379"

  catalogservice_db:
    image: postgres:16
    container_name: catalog_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret-postgres
      POSTGRES_DB: catalog_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata_catalog:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d catalog_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_catalog: