services:
  authservice_db:
    image: redis:alpine
    container_name: auth_redis
    command: redis-server --requirepass secret-redis
    ports:
      - "6379:6379"

  catalogservice_db:
    image: postgres:latest
    container_name: catalog_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret-postgres
      POSTGRES_DB: catalog_db
    ports:
      - "5435:5435"
    volumes:
      - pgdata_catalog:/var/lib/postgresql/data

volumes:
  pgdata_catalog: